### ISSUE TITLE
How to evaluate PDPU

### ISSUE THREAD

**Issue by wwwuxy** [qleenju/PDPU#2]
您好，我拜读了您关于PDPU的文章，在评估阶段我有一个简单的问题，想请教一下您如何在PDPU上进行DNN的准确度评估？

**Comment by qleenju** [comment]
您好，感谢关注。
具体而言，我们提取了ResNet网络第一个卷积层的激活、权重和输出（基于FP64格式），将激活和权重数据转换为相应的Posit格式，送入PDPU中完成计算后，将计算结果与原本的FP64格式的输出对比即可得到运算的准确率信息。
注：矩阵乘法本质上即为点积计算，因此送入PDPU中也是完成点积运算，为了避免偶然性，可以取较多次点积运算准确率的平均值作为最终结果。此外，单次点积运算的规模可能较大，可以拆解为多个小的点积运算。

**Comment by wwwuxy** [comment]
非常感谢您的回复，请问在转换为Posit格式这块，文章中并未介绍，请问相关方法是否开源呢？

**Comment by qleenju** [comment]
> 非常感谢您的回复，请问在转换为Posit格式这块，文章中并未介绍，请问相关方法是否开源呢？

这些可以通过软件来完成，比如常见的如SoftPosit库等

**Comment by wwwuxy** [comment]
好的，我会跟随您的工作进行尝试，感谢您的开源~
